//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWindowsHardwareInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ComputerConfigure
    {
        public int ID { get; set; }
        public string CPU { get; set; }
        public string Memory { get; set; }
        public string HardDisk { get; set; }
        public string GraphicsCard { get; set; }
        public string Display1 { get; set; }
        public string Display2 { get; set; }
        public string DigitalPlate { get; set; }
        public string MAC { get; set; }
        public string IP { get; set; }
        public string HostName { get; set; }
        public string UserName { get; set; }
        public string LastUpdated { get; set; }
    }
}
